services:
 webserver:
  image: nginx
  volumes:
#   - ./nginx/nginx-static-files/:/usr/share/nginx/html
   - ./php/public/:/usr/share/nginx/html
   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  networks:
   - webnet

 backend-phpfpm:
  build:
   context: . 
   dockerfile: Dockerfile
  volumes:
   - ./:/var/www/html
  networks:
   - webnet

 db:
  image: postgres:15
  environment:
   POSTGRES_DB: ${DB_NAME}
   POSTGRES_USER: ${DB_USER}
   POSTGRES_PASSWORD: ${DB_PASSWORD}
  volumes:
   - pgdata:/var/lib/postgresql/data
  networks:
   - webnet

volumes:
 pgdata:

networks:
 webnet:
